[package]
name = "simplews"
version = "0.0.1"
edition = "2021"
authors = ["Dario Caruso"]
description = "simple crate to use websockets"
license = "Apache-2.0"
documentation = "https://docs.rs/simplews"


[dependencies]
anyhow = "1.0.75"
futures-util = "0.3.29"
kanal = "0.1.0-pre8"
rustls = { version = "0.21.8", features = [
    "dangerous_configuration",
    "secret_extraction",
] }
tokio = { version = "1.33.0", features = ["macros","rt-multi-thread","time"] }
tokio-tungstenite = { version = "0.20.1", features = [
    "rustls",
    "rustls-native-certs",
    "rustls-tls-native-roots",
    "tokio-rustls",
    "webpki-roots",
] }
url = "2.4.1"
